version: "3"
services:
  web:
    image: nginx:alpine
    deploy:
      replicas: 15
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  portainer:
    image: portainer/portainer
    restart: always
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  portainerdata:
